<?php

return array(

    'debug' => env('WECHAT_JS_DEBUG', false),

    'jsApiList' => [
//        'onMenuShareTimeline',
//        'onMenuShareAppMessage',
//        'onMenuShareQQ',
//        'onMenuShareWeibo',
//        'onMenuShareQZone',
//        'startRecord',
//        'stopRecord',
//        'onVoiceRecordEnd',
//        'playVoice',
//        'pauseVoice',
//        'stopVoice',
//        'onVoicePlayEnd',
//        'uploadVoice',
//        'downloadVoice',
//        'chooseImage',
//        'previewImage',
//        'uploadImage',
//        'downloadImage',
//        'translateVoice',
//        'getNetworkType',
//        'openLocation',
//        'getLocation',
//        'hideOptionMenu',
//        'showOptionMenu',
//        'hideMenuItems',
//        'showMenuItems',
//        'hideAllNonBaseMenuItem',
//        'showAllNonBaseMenuItem',
//        'closeWindow',
//        'scanQRCode',
//        'chooseWXPay',
//        'openProductSpecificView',
//        'addCard',
//        'chooseCard',
//        'openCard',
    ],

);
